### ISSUE TITLE
[REVIEW]: PyMS: Python for Mycorrhizal Symbiosis data analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1125]
**Submitting author:** @jschnab (<a href="http://orcid.org/0000-0002-9515-332X">Jonathan Schnabel</a>)
**Repository:** <a href="https://github.com/jschnab/pyms-plot" target ="_blank">https://github.com/jschnab/pyms-plot</a>
**Version:** 0.9.0
**Editor:** @arfon
**Reviewer:** @aokad, @johnlees
**Archive:** <a href="https://doi.org/10.5281/zenodo.2567459" target="_blank">10.5281/zenodo.2567459</a>

## Status

[![status](http://joss.theoj.org/papers/2919aa7c97ac46489879aabdbd8f06a9/status.svg)](http://joss.theoj.org/papers/2919aa7c97ac46489879aabdbd8f06a9)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/2919aa7c97ac46489879aabdbd8f06a9"><img src="http://joss.theoj.org/papers/2919aa7c97ac46489879aabdbd8f06a9/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/2919aa7c97ac46489879aabdbd8f06a9/status.svg)](http://joss.theoj.org/papers/2919aa7c97ac46489879aabdbd8f06a9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jschnab/pyms" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@aokad & @johnlees, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jschnab/pyms">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.9.0
- [x] **Authorship:** Has the submitting author (@jschnab) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jschnab/pyms">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.9.0
- [x] **Authorship:** Has the submitting author (@jschnab) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @aokad, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01125/joss.01125/10.21105.joss.01125.pdf)

**Comment by arfon** [comment]
@aokad, @johnlees - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by johnlees** [comment]
@jschnab I've given this a go and confirmed it works with the test data. I've opened a few specific issues that will need to be addressed to meet the requirements for JOSS. My suggestion of making this into a package would definitely help with the stated goal of making this analysis easier for people who don't use the command line (typing `pip install pyms` is ok, but needing to explicitly do the same for the dependencies and cloning the github may put people off).

Some comments on the software/functionality you may also wish to take into account:

- It would be easier to specify the output directory for the statistical tests and saving the plot (also, this will be required if the input directory is not writable).
- Rather than needing to click 'analyze csv file' and find the input file again every time the settings (colour etc) are changed, it would probably be better to automatically redraw the plot when one of the menu options is chosen.
- When choosing the samples to perform statistics on, a 'select all' option might be helpful.

I also get the following message on exit:
```
Traceback (most recent call last):
  File "pyms.py", line 592, in <module>
    app.master.destroy()
  File "/Users/leesj01/anaconda3/envs/limix/lib/python3.6/tkinter/__init__.py", line 2062, in destroy
    self.tk.call('destroy', self._w)
_tkinter.TclError: can't invoke "destroy" command: application has been destroyed
```

Otherwise, looks good!

**Comment by aokad** [comment]
@jschnab I think that the following content is missing.

 1. Supporting Python versions (pyms will not work in python 2.7)
 2. "tkinter" in the dependency packages.
 3. Required version of pandas.  
 I get the following error on "Analyze csv file" choose "test_colonization.csv". The isna alias for isnull was only added in version 0.21 (0.23 is the latest release)

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\lib\tkinter\__init__.py", line 1559, in __call__
    return self.func(*args)
  File "pyms.py", line 351, in process_csv
    Global.col = Global.col.loc[~pd.isna(Global.col[index_name])]
AttributeError: module 'pandas' has no attribute 'isna'
```

**Comment by aokad** [comment]
@jschnab I get the following error on "Save as" choose the file type.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\lib\tkinter\__init__.py", line 1559, in __call__
    return self.func(*args)
  File "pyms.py", line 210, in saveas_pdf
    plt.savefig(fname=fi_name, bbox_inches='tight')
  File "C:\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\lib\site-packages\matplotlib\pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "C:\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\lib\site-packages\matplotlib\figure.py", line 1572, in savefig
    self.canvas.print_figure(*args, **kwargs)
TypeError: print_figure() missing 1 required positional argument: 'filename'
```

**Comment by jschnab** [comment]
@aokad @johnlees  thank you for your comments, I'm working on it.

**Comment by arfon** [comment]
:wave: @jschnab - how are you getting along making your changes?

**Comment by jschnab** [comment]
@arfon - Hi, I was in the process of moving to the US so I only started working on it this week. My plan is to finish addressing the comments within the next two weeks.

**Comment by arfon** [comment]
> @arfon - Hi, I was in the process of moving to the US so I only started working on it this week. My plan is to finish addressing the comments within the next two weeks.

Got it. Thanks for the update.

**Comment by arfon** [comment]
> @arfon - Hi, I was in the process of moving to the US so I only started working on it this week. My plan is to finish addressing the comments within the next two weeks.

Friendly reminder to get to this soon please @jschnab.

**Comment by jschnab** [comment]
@ wedon commands

**Comment by jschnab** [comment]
@wedon generate pdf

**Comment by jschnab** [comment]
@aokad Hello, I update README.md to specify that PyMS is written in Python 3, the required version of pandas (0.23) and that TkInter is required (I thought it was "vanilla" Python). The error happening when print_figure() is called is solved when pandas 0.23 is used (cf your 2nd comment).

**Comment by jschnab** [comment]
@johnlees Hello, I added the possibility to select the output directory, I added a "select all" function for genotypes in the statistical analysis, I corrected the error when closing the window.

Now I'm working on the automatic plot re-drawing after modification of graphical parameters, and then I'll make a conda package.

Thank you all for your patience.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01125/joss.01125/10.21105.joss.01125.pdf)

**Comment by johnlees** [comment]
> @johnlees Hello, I added the possibility to select the output directory, I added a "select all" function for genotypes in the statistical analysis, I corrected the error when closing the window.
> 
> Now I'm working on the automatic plot re-drawing after modification of graphical parameters, and then I'll make a conda package.
> 
> Thank you all for your patience.

This all looks good to me, pending the creation of a conda/pip package

**Comment by aokad** [comment]
I checked all the boxes, everything looks good.

**Comment by jschnab** [comment]
@arfon @aokad @johnlees 
Hi, I added automatic replot when changing color and bar aggregation.

I made a pip package for PyPI but there is already a project called "pyms". I was going to rename my Github repository "pymsplot", can I keep the same JOSS submission? How do I update the link to the GitHub repository in the paper?

**Comment by arfon** [comment]
> I made a pip package for PyPI but there is already a project called "pyms". I was going to rename my Github repository "pymsplot", can I keep the same JOSS submission? How do I update the link to the GitHub repository in the paper?

I can do this. Please go ahead and change the name and I'll update the details here.

**Comment by jschnab** [comment]
@arfon I uploaded the PyMS package on PyPI under the name pyms-plot. I changed the name of the repository on GitHub to pyms-plot.

**Comment by arfon** [comment]
@jschnab - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by jschnab** [comment]
@arfon - I uploaded an archive on Zenodo the DOI is 10.5281/zenodo.2567459
By the way I updated the version of the software : 0.9.0

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.2567459 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2567459" target="_blank">10.5281/zenodo.2567459</a> is the archive.

**Comment by arfon** [comment]
@whedon set 0.9.0 as version

**Comment by whedon** [comment]
OK. 0.9.0 is the version.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1125 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1125 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:73:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/ 10.1109/MCSE.2007.55  is OK
- http://doi.org/ 10.1111/j.1365-313X.2006.02785.x  is OK
- http://doi.org/ 10.1111/nph.14936  is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01125/joss.01125/10.21105.joss.01125.pdf)

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/ 10.1109/MCSE.2007.55  is OK
- http://doi.org/ 10.1111/j.1365-313X.2006.02785.x  is OK
- http://doi.org/ 10.1111/nph.14936  is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/498

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/498, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@jschnab - it looks like there's an issue with one of the citations in the first paragraph?

**Comment by jschnab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01125/joss.01125/10.21105.joss.01125.pdf)

**Comment by jschnab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01125/joss.01125/10.21105.joss.01125.pdf)

**Comment by jschnab** [comment]
@arfon - I corrected mistakes in paper.md

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/503

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/503, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/ 10.1109/MCSE.2007.55  is OK
- http://doi.org/ 10.1111/j.1365-313X.2006.02785.x  is OK
- http://doi.org/ 10.1111/nph.14936  is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/504
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01125](https://doi.org/10.21105/joss.01125)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@aokad, @johnlees - many thanks for your reviews here ✨ 

@jschnab - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01125/status.svg)](https://doi.org/10.21105/joss.01125)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01125">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01125/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01125/status.svg
   :target: https://doi.org/10.21105/joss.01125
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01125/status.svg)](https://doi.org/10.21105/joss.01125)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
